### ISSUE TITLE
allow to suppress downloading message

### ISSUE THREAD

**Issue by nuest** [noerw/opensensmapR#11]
[Here](https://github.com/noerw/opensensmapR/blob/master/R/api.R#L55) `httr::progress()` is always used. It would be useful to be able to turn this off when calling `osem_()` functions, maybe

```r
osem_boxes(, progress = NULL)
```

while keeping the default.

Try out using the function within an R Markdown document (yes, you can hide chunk output, but only for the whole chunk):

````markdown
---
title: "Test"
author: "Daniel Nüst"
date: "1/4/2018"
output: html_document
---

```{r}
library("opensensemapr")

osem_measurements("PM2.5")
```


```{r}
sessionInfo()
```
````

![image](https://user-images.githubusercontent.com/1325054/34570760-077d91ec-f16d-11e7-9762-e36a7266c683.png)

**Comment by noerw** [comment]
I see the issue. However I don't like to pass even more arguments for a feature which should just make the user's life simpler.
What do you think about automatically suppressing the output in non-interactive sessions like knitr instead?

**Comment by nuest** [comment]
Well, more parameters with a default do not really impact regular user experience IMHO.

But handling it automatically for knitr sounds great.
