### ISSUE TITLE
Move to senseBox organisation

### ISSUE THREAD

**Issue by nuest** [noerw/opensensmapR#18]
As a user it would have helped me to find this package if it would be part of the [senseBox](https://github.com/sensebox/) organisation. Have you discussed this already?

Especially because there is a very early draft of an R package there, too: https://github.com/sensebox/oSeM-R-package (which can be confusing)

**Comment by noerw** [comment]
I would be fine with that. ping @ubergesundheit

**Comment by ubergesundheit** [comment]
Also Fine with me! Is there anything that should be done before the org change?

**Comment by noerw** [comment]
Sorry, I totally forgot about this.
I would keep maintainership, so there is nothing to change.

@mpfeil is this still of interest? Whats the status of the [oSeM-R-package](https://github.com/sensebox/oSeM-R-package)?

**Comment by mpfeil** [comment]
@noerw this is still of interest and we can transfer it to our organization.

[oSeM-R-package](https://github.com/sensebox/oSeM-R-package) is outdated and not used anymore. We can add a `deprecation notice` to the `README` and link to this repository.

**Comment by noerw** [comment]
done! need to check if CI is still working, but it's looking good.

**Comment by mpfeil** [comment]
Going to add the notice to the other repository this week. Thanks for transfering!
