### ISSUE TITLE
Pass ... paramaters to plot function in plot.sensebox

### ISSUE THREAD

**Issue by nuest** [noerw/opensensmapR#24]
It would be cool to be able to adjust plotting options when simply doing `plot(my_boxes)`, see https://github.com/noerw/opensensmapR/blob/925909ebe85382fb041cac85f49018680ad2bacc/R/box_utils.R#L25 where `...` could be forwarded.

**Comment by noerw** [comment]
Oh, I thought `...` was already passed on. Will add it!
